# Makefile -
#

ADDED_CFLAGS += -Wall
ADDED_INCFLAGS += -I$(VMX_BASE)/include/ugl

OBJS = udcbcopy.o udcmset.o udcclr.o uglugi.o
SUBDIRS =
LIB_TGT = ugl-driver

include $(VMX_BASE)/include/make/build.defaults
