 ##############################################################################
 #   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 #
 #   This file is part of Real VMX.
 #   Copyright (C) 2013 Surplus Users Ham Society
 #
 #   Real VMX is free software: you can redistribute it and/or modify
 #   it under the terms of the GNU General Public License as published by
 #   the Free Software Foundation, either version 3 of the License, or
 #   (at your option) any later version.
 #
 #   Real VMX is distributed in the hope that it will be useful,
 #   but WITHOUT ANY WARRANTY; without even the implied warranty of
 #   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 #   GNU General Public License for more details.
 #
 #   You should have received a copy of the GNU General Public License
 #   along with Real VMX.  If not, see <http://www.gnu.org/licenses/>.
 #

# Makefile - I/O library for Real VMX

OBJS = objLib.o classLib.o classShow.o memPartLib.o memLib.o memShow.o \
       errnoLib.o ffsLib.o taskHookLib.o taskHookShow.o pathLib.o iosLib.o \
       iosShow.o ioLib.o dirLib.o tyLib.o logLib.o excLib.o symLib.o symShow.o \
       uioLib.o unixLib.o selectLib.o erfLib.o nullDrv.o pipeDrv.o
SUBDIRS =
LIB_TGT = os

include $(VMX_BASE)/include/make/build.defaults

