# Makefile -
#

OBJS = netBufLib.o netShow.o netLib.o sockLib.o bsdSockLib.o mbufLib.o \
       soLib.o sbLib.o ifLib.o radixLib.o routeLib.o rawLib.o unixDomainLib.o
SUBDIRS =
LIB_TGT = net

include $(VMX_BASE)/include/make/build.defaults
