# Makefile -
#

OBJS = ugldib.o uglmdib.o ugltdib.o uglcolor.o uglgc.o uglmode.o uglpixel.o \
       uglline.o uglrect.o uglpoly.o uglcursr.o uglbatch.o uglmem.o uglregn.o \
       uglfont.o
SUBDIRS =
LIB_TGT = ugl-2d

include $(VMX_BASE)/include/make/build.defaults
