# Makefile -
#

OBJS = ugldib.o uglmdib.o ugltdib.o uglcolor.o uglgc.o uglmode.o uglpixel.o \
       uglbatch.o uglmem.o uglregn.o
SUBDIRS =
LIB_TGT = ugl-2d

include $(VMX_BASE)/include/make/build.defaults
