 ##############################################################################
 #   DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 #
 #   This file is part of Real VMX.
 #   Copyright (C) 2013 Surplus Users Ham Society
 #
 #   Real VMX is free software: you can redistribute it and/or modify
 #   it under the terms of the GNU General Public License as published by
 #   the Free Software Foundation, either version 3 of the License, or
 #   (at your option) any later version.
 #
 #   Real VMX is distributed in the hope that it will be useful,
 #   but WITHOUT ANY WARRANTY; without even the implied warranty of
 #   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 #   GNU General Public License for more details.
 #
 #   You should have received a copy of the GNU General Public License
 #   along with Real VMX.  If not, see <http://www.gnu.org/licenses/>.
 #

# Makefile - Real VMX Operating System library

OBJS = errnoLib.o classLib.o objLib.o memPartLib.o kernelLib.o workQLib.o \
       vmxLib.o taskLib.o taskInfo.o taskShow.o taskHookLib.o tickLib.o \
       wdLib.o ffsLib.o semLib.o semBLib.o semMLib.o semCLib.o msgQLib.o \
       msgQInfo.o
SUBDIRS =
LIB_TGT = vmx

include $(VMX_BASE)/include/make/build.defaults

