# Makefile -
#

ADDED_INCFLAGS += -I$(VMX_BASE)/include/ugl

OBJS = ufcbi08.o ufcbr08.o ufcni08.o ufcnr08.o \
       ufcbi10.o ufcbr10.o ufcni10.o ufcnr10.o \
       ufcbi12.o ufcbr12.o ufcni12.o ufcnr12.o \
       ufcbi14.o ufcbr14.o ufcni14.o ufcnr14.o \
       ufcbi18.o ufcbr18.o ufcni18.o ufcnr18.o \
       ufcbi24.o ufcbr24.o ufcni24.o ufcnr24.o \
       ufhbi08.o ufhbr08.o ufhni08.o ufhnr08.o \
       ufhbi10.o ufhbr10.o ufhni10.o ufhnr10.o \
       ufhbi12.o ufhbr12.o ufhni12.o ufhnr12.o \
       ufhbi14.o ufhbr14.o ufhni14.o ufhnr14.o \
       ufhbi18.o ufhbr18.o ufhni18.o ufhnr18.o \
       ufhbi24.o ufhbr24.o ufhni24.o ufhnr24.o \
       uftbi08.o uftbr08.o uftni08.o uftnr08.o \
       uftbi10.o uftbr10.o uftni10.o uftnr10.o \
       uftbi12.o uftbr12.o uftni12.o uftnr12.o \
       uftbi14.o uftbr14.o uftni14.o uftnr14.o \
       uftbi18.o uftbr18.o uftni18.o uftnr18.o \
       uftbi24.o uftbr24.o uftni24.o uftnr24.o

SUBDIRS =
LIB_TGT = ugl-fonts

include $(VMX_BASE)/include/make/build.defaults
