# Makefile -
#

OBJS = ufcbi08.o ufcbr08.o ufcni08.o ufcnr08.o \
       ufcbi10.o ufcbr10.o ufcni10.o ufcnr10.o \
       ufcbi12.o ufcbr12.o ufcni12.o ufcnr12.o \
       ufcbi14.o ufcbr14.o ufcni14.o ufcnr14.o \
       ufcbi18.o ufcbr18.o ufcni18.o ufcnr18.o \
       ufcbi24.o ufcbr24.o ufcni24.o ufcnr24.o
SUBDIRS =
LIB_TGT = ugl-fonts

include $(VMX_BASE)/include/make/build.defaults
