# Makefile -
#

OBJS = ufcbi08.o ufcbr08.o ufcni08.o ufcnr08.o \
       ufcbi10.o ufcbr10.o ufcni10.o ufcnr10.o \
       ufcbi12.o ufcbr12.o ufcni12.o ufcnr12.o \
       ufcbi14.o ufcbr14.o ufcni14.o ufcnr14.o \
       ufcbi18.o ufcbr18.o ufcni18.o ufcnr18.o \
       ufcbi24.o ufcbr24.o ufcni24.o ufcnr24.o \
       ufhbi08.o ufhbr08.o ufhni08.o ufhnr08.o \
       ufhbi10.o ufhbr10.o ufhni10.o ufhnr10.o \
       ufhbi12.o ufhbr12.o ufhni12.o ufhnr12.o \
       ufhbi14.o ufhbr14.o ufhni14.o ufhnr14.o \
       ufhbi18.o ufhbr18.o ufhni18.o ufhnr18.o \
       ufhbi24.o ufhbr24.o ufhni24.o ufhnr24.o

SUBDIRS =
LIB_TGT = ugl-fonts

include $(VMX_BASE)/include/make/build.defaults
