# Makefile -
#

ADDED_CFLAGS += -Wall
ADDED_INCFLAGS += -I$(VMX_BASE)/include/ugl

OBJS = udgclri.o udgenclp.o udgengc.o udgmode.o udgtbmp.o udgenlin.o \
       udgenfil.o udgenrec.o udgenply.o udgencrs.o udg8clr.o
SUBDIRS = 8bit
LIB_TGT = ugl-driver

include $(VMX_BASE)/include/make/build.defaults
