# Makefile -
#

OBJS = udvgabmp.o udvgaclr.o udvgagc.o udvgapix.o udvgalin.o udvga.o \
       udvgadev.o udvgainf.o udvgamode.o
SUBDIRS =
LIB_TGT = ugl-driver

include $(VMX_BASE)/include/make/build.defaults
