# Makefile -
#

OBJS = ext2ConvLib.o ext2SuperLib.o ext2fsLib.o ext2SyncerVopsLib.o \
       ext2VfsLib.o ext2VopsLib.o usrExt2.o

SUBDIRS = 
LIB_TGT = fs

include $(VMX_BASE)/include/make/build.defaults

