# Makefile -
#

OBJS = inLib.o ipLib.o icmpLib.o rawIpLib.o tcpLib.o udpLib.o inetLib.o \
       uipc_dom.o
SUBDIRS =
LIB_TGT = netinet

ADDED_DFLAGS += -DDIAGNOSTIC

include $(VMX_BASE)/include/make/build.defaults
